# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kyle Hyams | Designer
email: hello@kylehya.ms
description: > # this means to ignore newlines until "baseurl:"
  Kyle Hyams is an Experience Designer from Orlando, Florida. He focuses on web design and animation, but also appreciates brand design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylehya.ms" # the base hostname & protocol for your site
twitter_username: kylehyams
github_username:  kylehyams

# Build settings
markdown: kramdown
exclude:
  - gulpfile.js
  - node_modules
  - package.json
  - README.md
  - about.md # Remove in the future!

# Portfolio settings
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/